### ISSUE TITLE
Math.Between de Phaser genera numeros con decimales

### ISSUE THREAD

**Issue by Moromon** [AdrianAlbarran/CookieMayhem-JuegosEnRed#31]
Muy de vez en cuando al realizar el math between phaser genera un numero con decimales, destrozando la interfaz
Se podría solucionar un math floor

**Comment by AdrianAlbarran** [comment]
Resolved by Adrian "PinguinoTocho"

**Comment by AdrianAlbarran** [comment]
Resolved by Adrian "PinguinoTocho"
